# Generated by Django 4.2.4 on 2023-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='module_code',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
